### ISSUE TITLE
Validate

### ISSUE THREAD

**Issue by bxrdy** [Brijesh097/book-my-ticket#1]
Validate **login.php** , **register.php** and **recharge.php**

**Comment by rmoswela** [comment]
Hi, do you mean cleaning the data, that is to be sent to the database?

**Comment by rmoswela** [comment]
@Brijesh097 i want to take this one

**Comment by bxrdy** [comment]
@rmoswela Yes

**Comment by bxrdy** [comment]
Validation is now done! Closing this issue.
